### ISSUE TITLE
Consider Supporting Optional Light Mode Color Scheme

### ISSUE THREAD

**Issue by DaveLak** [itzCozi/markd#4]
### What?

I'd like to propose adding support for an optional "light" color scheme for the app UI. 

### Why?
 
Right now it appears that UI is always set to use black/dark UI styles (which look great IMO) but I find it can be difficult to see what I'm doing if I happen to be using the app in a sunny or high screen glare environments.

Inverting the dark background and light text in such situations can make the overall experience much better in those situations.

### How?

I'd suggest considering implementation via [the light mode / dark mode support that's built into tailwind)[https://tailwindcss.com/docs/dark-mode) and:

- Default would be whatever the users `prefers-color-scheme` value is.
- Allow the active mode to be manually set via something like a toggle in the navigation menu with 3 states: light/dark/auto.

---

What do you think?

In any case, thanks for sharing this slick app 🙂

**Comment by Pasithea0** [comment]
Added in a4a67b9d454d4d4f9a56aec64eb6e983b3b229d3
